env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types":0,
  "react/destructuring-assignment":0,
  "max-len": "off",
  "anchor-is-valid": "off",
  "anchor-has-content": "off",
  "linebreak-style": 0,
  "consistent-return": "off",
  "indent": ["error", 4],
  "react/jsx-indent": ["error", 4],
  "eslint no-tabs": ["error", { allowIndentationTabs: false }],
  "no-tabs-in-file": 1,
  no-confusing-arrow: ["error", {"onlyOneSimpleParam": true}]
  
}
settings:
  import/resolver:
    alias:
      '@components': path.resolve(__dirname, 'src/components')
      '@api': path.resolve(__dirname, 'src/api')
      '@utils': path.resolve(__dirname, 'src/utils')
      '@assets': path.resolve(__dirname, 'src/assets')
      '@ui': path.resolve(__dirname, 'src/ui')
