# docker-compose.yaml
version: '3.7'

services:
  rs-minio-service:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: rs_minio_user
      MINIO_ROOT_PASSWORD: rsminio777
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - apps

  rs-db-service:
    image: postgres:13
    ports:
      - 9002:5432
    environment:
      - POSTGRES_USER=rs_user
      - POSTGRES_DB=rs_db
      - POSTGRES_PASSWORD=rs7854#90
    volumes:
      - "rs-db-data:/var/lib/postgresql/data"
    networks:
      - apps

  rs-backend-service:
    image: 'rs-backend-image'
    build:
      context: ./backend/restapi
      dockerfile: Dockerfile.development
    ports:
      - 9003:9003
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rs-db-service/rs_db
      - SPRING_DATASOURCE_USERNAME=rs_user
      - SPRING_DATASOURCE_PASSWORD=rs7854#90
      - SPRING_MINIO_SERVER=http://rs-minio-service:9000
    depends_on:
      - rs-db-service
    networks:
      - apps

  rs-frontend-service:
    image: 'rs-frontend-image'
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - 9004:9004
    depends_on:
      - rs-minio-service
      - rs-backend-service
    networks:
      - apps

volumes:
  rs-db-data:
  minio-storage:

networks:
  apps: