/* eslint-disable */
export const REST_ERRORS = {
    INCORRECT_REQUEST_ERROR: 10000,
    INCORRECT_OLD_PASSWORD: 10001,
    AUTH_ERROR: 10100,
    CONFIRM_EMAIL_ERROR: 10101,
    KEYCLOAK_ERROR: 10104,
    RESET_TIMEOUT_ERROR: 10105,
    RESET_TOKEN_ERROR: 10106,
    CONTENT_NOT_FOUND: 10400,
    SERVER_ERROR: 10500,
    DLC_DB_ERROR: 10501,
    DATA_FORMAT_ERROR: 10502,
    S3_ERROR: 10503,
    ACCESS_TOKEN_ERROR: 10900,
    USER_ALREADY_REGISTERED: 10901,
};

export const REST_ERRORS_LIST = [
    REST_ERRORS.INCORRECT_REQUEST_ERROR,
    REST_ERRORS.INCORRECT_OLD_PASSWORD,
    REST_ERRORS.AUTH_ERROR,
    REST_ERRORS.CONFIRM_EMAIL_ERROR,
    REST_ERRORS.KEYCLOAK_ERROR,
    REST_ERRORS.RESET_TIMEOUT_ERROR,
    REST_ERRORS.RESET_TOKEN_ERROR,
    REST_ERRORS.CONTENT_NOT_FOUND,
    REST_ERRORS.SERVER_ERROR,
    REST_ERRORS.DLC_DB_ERROR,
    REST_ERRORS.DATA_FORMAT_ERROR,
    REST_ERRORS.S3_ERROR,
    REST_ERRORS.ACCESS_TOKEN_ERROR,
    REST_ERRORS.USER_ALREADY_REGISTERED
]

export const INNER_ERROR = {
    LOGIN_VALIDATION_ERROR: 9998,
    PASS_VALIDATION_ERROR: 9999,
}

export const UNEXPECTED_ERRORS = [
    REST_ERRORS.KEYCLOAK_ERROR,
    REST_ERRORS.SERVER_ERROR,
    REST_ERRORS.DLC_DB_ERROR,
    REST_ERRORS.S3_ERROR];
